### ISSUE TITLE
手順通りに動かすと MODULE_NOT_FOUND が発生する

### ISSUE THREAD

**Issue by nakkaa** [fono09/ttRelay#12]
## 環境
* OS: Raspbian GNU/Linux 10 (buster)
* Docker version 19.03.12
* docker-compose version 1.26.0

## 発生事象
READMEにある通り、config/default.jsonを作成して `docker-compose up` を実行すると
以下のエラー `MODULE_NOT_FOUND` が発生しコンテナが再起動を繰り返します。

```text
node_1   | > tt-relay@1.0.0 start /home/node/app
node_1   | > node index.js
node_1   | 
node_1   | internal/modules/cjs/loader.js:1083
node_1   |   throw err;
node_1   |   ^
node_1   | 
node_1   | Error: Cannot find module 'websocket'
node_1   | Require stack:
node_1   | - /home/node/app/index.js
node_1   |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
node_1   |     at Function.Module._load (internal/modules/cjs/loader.js:923:27)
node_1   |     at Module.require (internal/modules/cjs/loader.js:1140:19)
node_1   |     at require (internal/modules/cjs/helpers.js:75:18)
node_1   |     at Object.<anonymous> (/home/node/app/index.js:2:23)
node_1   |     at Module._compile (internal/modules/cjs/loader.js:1251:30)
node_1   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
node_1   |     at Module.load (internal/modules/cjs/loader.js:1100:32)
node_1   |     at Function.Module._load (internal/modules/cjs/loader.js:962:14)
node_1   |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
node_1   |   code: 'MODULE_NOT_FOUND',
node_1   |   requireStack: [ '/home/node/app/index.js' ]
```

## 再現手順

1. 以下を実施する。
```
git clone https://github.com/fono09/ttRelay
cd ttRelay
docker-compose run --rm node npm
```

実行結果
```
nakkaa@pi200606:~/ttRelay $ docker-compose run --rm node npm
Creating network "ttrelay_backend" with the default driver
Creating ttrelay_redis_1 ... done
Pulling node (node:alpine)...
alpine: Pulling from library/node
3cfb62949d9d: Already exists
a69bb8481446: Pull complete
998710ebc560: Pull complete
0ababa642a65: Pull complete
Digest: sha256:a016fdfb6001b49c6d99a662eddf79de2e382814ed1e04b0c5e113587d8a6aec
Status: Downloaded newer image for node:alpine

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /home/node/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config
```

2. `config/default.json` を作成する。
3. `docker-compose up` を実行する。

**Comment by nakkaa** [comment]
```
nakkaa@pi200606:~/ttRelay $ docker-compose run --rm node npm i
Starting ttrelay_redis_1 ... done
npm WARN checkPermissions Missing write access to /home/node/app
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /home/node/app
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/home/node/app'
npm ERR!  [Error: EACCES: permission denied, access '/home/node/app'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/node/app'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-09-04T12_18_16_769Z-debug.log
```

**Comment by nakkaa** [comment]
```
git clone https://github.com/fono09/ttRelay
chmod 777 ttRelay
cd ttRelay
docker-compose run --rm node npm i
```

で動いた

**Comment by nakkaa** [comment]
動いてなかった
```
nakkaa@pi200606:~/ttRelay $ docker-compose run --rm node npm i
Creating network "ttrelay_backend" with the default driver
Creating ttrelay_redis_1 ... done
audited 66 packages in 6.252s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by nakkaa** [comment]
```
nakkaa@pi200606:~/ttRelay $ docker-compose run --rm node npm i
Creating network "ttrelay_backend" with the default driver
Creating ttrelay_redis_1 ... done

> bufferutil@4.0.1 install /home/node/app/node_modules/bufferutil
> node-gyp-build

gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:468:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Linux 5.4.51-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node/app/node_modules/bufferutil
gyp ERR! node -v v14.8.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@4.0.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-09-04T12_39_23_277Z-debug.log
```

**Comment by fono09** [comment]
`docker-compose up -d` でやはり動作しているので再現しない。

**Comment by fono09** [comment]
これも検証が必要そう

**Comment by fono09** [comment]
> 動いてなかった
> 
> ```
> nakkaa@pi200606:~/ttRelay $ docker-compose run --rm node npm i
> Creating network "ttrelay_backend" with the default driver
> Creating ttrelay_redis_1 ... done
> audited 66 packages in 6.252s
> found 1 low severity vulnerability
>   run `npm audit fix` to fix them, or `npm audit` for details
> ```

これは動いているうちに入っていて。パッケージのインストールは完了している。

**Comment by fono09** [comment]
> gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python 


Pythonが入れると解決するように見える

**Comment by fono09** [comment]
> 手元のMacでも動かない
> 
> ```
> 2gimac-180418$ ~/ttRelay docker-compose run --rm node npm i
> Creating network "ttrelay_backend" with the default driver
> Creating ttrelay_redis_1 ... done
> 
> > bufferutil@4.0.1 install /home/node/app/node_modules/bufferutil
> > node-gyp-build
> 
> 
> > utf-8-validate@5.0.2 install /home/node/app/node_modules/utf-8-validate
> > node-gyp-build
> 
> added 76 packages from 84 contributors and audited 76 packages in 6.62s
> found 0 vulnerabilities
> 
> 2gimac-180418$ ~/ttRelay docker ps -a
> CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                   PORTS               NAMES
> 2f592c3ca55d        redis:latest        "docker-entrypoint.s…"   21 seconds ago      Up 19 seconds            6379/tcp            ttrelay_redis_1
> ```

この直後に `docker-compose up -d` をすれば動き出しそうな予感。

**Comment by nakkaa** [comment]
今やったら動いたのでcloseします。
